export const CHECK_IF_AUTHORIZED_START = 'CHECK_IF_AUTHORIZED_START';
export const CHECK_IF_AUTHORIZED_RESULT_TRUE = 'CHECK_IF_AUTHORIZED_RESULT_TRUE';
export const CHECK_IF_AUTHORIZED_RESULT_FALSE = 'CHECK_IF_AUTHORIZED_RESULT_FALSE';

export const FORM_VALIDATION_ERROR = 'FORM_VALIDATION_ERROR';
export const FORM_VALIDATION_ERROR_RESET = 'FORM_VALIDATION_ERROR_RESET';

export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SET_LOGIN_TAB_ACTIVE = 'SET_LOGIN_TAB_ACTIVE';
export const SET_REGISTER_TAB_ACTIVE = 'SET_REGISTER_TAB_ACTIVE';
