export const CHECK_IF_AUTHORIZED_START = 'CHECK_IF_AUTHORIZED_START';
export const CHECK_IF_AUTHORIZED_RESULT_TRUE = 'CHECK_IF_AUTHORIZED_RESULT_TRUE';
export const CHECK_IF_AUTHORIZED_RESULT_FALSE = 'CHECK_IF_AUTHORIZED_RESULT_FALSE';

export const FORM_VALIDATION_ERROR = 'FORM_VALIDATION_ERROR';
export const FORM_VALIDATION_ERROR_RESET = 'FORM_VALIDATION_ERROR_RESET';

export const REGISTRATION_START = 'REGISTRATION_START';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SET_LOGIN_TAB_ACTIVE = 'SET_LOGIN_TAB_ACTIVE';
export const SET_REGISTER_TAB_ACTIVE = 'SET_REGISTER_TAB_ACTIVE';

export const SET_USER = 'SET_USER';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GET_CHAT_MESSAGES_START = 'GET_CHAT_MESSAGES_START';
export const GET_CHAT_MESSAGES_SUCCESS = 'GET_CHAT_MESSAGES_SUCCESS';
export const GET_CHAT_MESSAGES_ERROR = 'GET_CHAT_MESSAGES_ERROR';