export const CHECK_IF_AUTHORIZED_START = 'CHECK_IF_AUTHORIZED_START';
export const CHECK_IF_AUTHORIZED_RESULT_TRUE = 'CHECK_IF_AUTHORIZED_RESULT_TRUE';
export const CHECK_IF_AUTHORIZED_RESULT_FALSE = 'CHECK_IF_AUTHORIZED_RESULT_FALSE';
